assistantlab/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
]


"""assistantlab URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
https://docs.djangoproject.com/en/3.1/topics/http/urls/
Examples:
Function views
1. Add an import:  from my_app import views
2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
1. Add an import:  from other_app.views import Home
2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
1. Import the include() function: from django.urls import include, path
2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # path('', views.index),
    path('', views.dasbor, name='dasbor'),
    path('akun/', views.akun, name='akun'),
    path('akun/edit/', views.editAkun, name='edit_akun'),

    path('training/', views.dataTraining, name='training'),
    path('training/add', views.createTraining, name='create_training'),
    path('training/update/<str:id>', views.updateTraining, name='update_training'),
    path('training/delete/<str:id>', views.deleteTraining, name='delete_training'),

    path('training/see-training/<str:id>', views.seeDataTraining, name="see_data_training"),
    path('training/update-training/<str:id>', views.updateDataTraining, name="update_data_training"),
    path('training/add-training/<str:id>', views.createDataTraining, name="create_data_training"),
    path('training/add-attribute/', views.createAttribute, name="create_attribute"),

    path('lab/', views.lab, name='lab'),
    path('lab/add/', views.createLab, name='create_lab'),
    path('lab/update/<str:id>', views.updateLab, name='update_lab'),
    path('lab/delete/<str:id>', views.deleteLab, name='delete_lab'),

    path('pakar/knn/', views.pakarKNN, name='pakar_knn'),
]

home/models.py
from django.db import models

# Create your models here.
class Lab(models.Model):
    name  = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Training(models.Model):
    name = models.CharField(max_length=200, null=True)
    result= models.ForeignKey(Lab ,null=True, on_delete=models.SET_NULL)
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

class Attribute(models.Model):
    name  = models.CharField(max_length=200, null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.name

class TrainingValue(models.Model):
    training_id = models.ForeignKey(Training ,null=True, on_delete=models.SET_NULL)
    attribute_id = models.ForeignKey(Attribute ,null=True, on_delete=models.SET_NULL)
    value = models.FloatField(null=True)
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.training_id)+": "+str(self.attribute_id)+"("+str(self.value)+")"

home/forms.py
from django import forms
from django.forms import ModelForm
from .models import *

class LabForm(ModelForm):
    class Meta:
        model = Lab
        fields = ['name']
        # fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }

class TrainingForm(ModelForm):
    class Meta:
        model = Training
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'result': forms.Select(attrs={'class': 'form-control'}),
        }

class DataTrainingForm(ModelForm):
    class Meta:
        model = TrainingValue
        fields = '__all__'
        widgets = {
            'attribute_id': forms.Select(attrs={'class': 'form-control'}),
            'training_id': forms.Select(attrs={'class': 'form-control'}),
            'value': forms.NumberInput(attrs={'class': 'form-control','step': '0.01'}),
        }

home/views.py
from django.urls import reverse
from django.db.models import Count
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.forms import formset_factory, modelformset_factory
from .models import *
from .models import TrainingValue
from .models import Training as TrainingModel
from .forms import *

# Create your views here.
def pakarKNN(request):
    trainings = TrainingModel.objects.all()
    amount_training = trainings.count()
    attr = Attribute.objects.all()
    amount_attr = attr.count()
    raw = []
    for training in trainings:
        dtrain   = TrainingValue.objects.filter(training_id=training.id)
        attribute = []
        for train in dtrain:
            attribute.append(train.value)
        raw.append([attribute, training.result])
    print("raw: ",raw)
    if request.method == "POST":
        # Menampung formulir insert
        insert = []
        for atr in attr:
            insert.append(float(request.POST.get('value-'+str(atr.id),'invalid')))
        print("insert: ",insert)

        bound = []
        #Metode Manhattan
        manhattan = []
        for i in range(amount_training): #training
            distance = 0
            for j in range(amount_attr): #atribut
                distance += abs(insert[j]-raw[i][0][j])
            bound.append({"d":distance,"r":raw[i][1]})
            manhattan.append(distance)
        print('manhattan: ', manhattan)
        #KNN
        hasil = knn(bound, manhattan, 9, amount_training)
        print(hasil)
    else:
        hasil = ''
    return render(request, 'pakar/knn.html', {'attr':attr, 'hasil':hasil})

def knn(data, manhattan, k, max_k):
    manhattan.sort()
    result = {}
    for d in data:
        if d['d'] <= manhattan[k-1]:
            result[d['r'].name] = result.get(d['r'].name, 0) + 1
            print(d['r'].name)
        else:
            print('-')
    #Frequency
    sorted_dict = {}
    sorted_keys = sorted(result, key=result.get, reverse=True)
    for w in sorted_keys:
        sorted_dict[w] = result[w]
    result = sorted_dict
    print(result)

    #Perbaikan
    key1 = list(result.keys())[0]
    key2 = list(result.keys())[1]

    if ( result[key1]==result[key2] and k+4 < max_k ):
        knn(data, manhattan, k+4, max_k)
    return {
        'result' : key1,
        'detail' : result,
        'k'      : k,
    }

def index(request):
    return render(request, 'front/landing.html')

def dasbor(request):
    return render(request, 'front/dasbor.html')

def akun(request):
    return render(request, 'akun/index.html')

def editAkun(request):
    return render(request, 'akun/editakun.html')

# TRAINING #
def dataTraining(request):
    trainings = TrainingModel.objects.all()
    data = {'trainings': trainings}
    return render(request, 'training/index.html', data)

def createTraining(request):
    form = TrainingForm()
    if request.method == "POST":
        form = TrainingForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('training'))
    data = {'form':form}
    return render(request, 'training/create.html', data)

def updateTraining(request, id):
    train = TrainingModel.objects.filter(pk=id).first()
    form = TrainingForm(instance=train)
    if not train:
        return redirect(reverse('create_training'))
    else:
        if request.method == "POST":
            form = TrainingForm(request.POST, instance=train)
            if form.is_valid():
                print(train.id)
                form.save()
                return redirect(reverse('training'))
    data = {'training':train,'form':form}
    return render(request, 'training/update.html', data)

def deleteTraining(request, id):
    train = TrainingModel.objects.filter(pk=id).first()
    if not train:
        return redirect(reverse('training'))
    else:
        train.delete()
    return redirect(reverse('training'))


# DATA TRAINING
def seeDataTraining(request, id):
    dtrain = TrainingValue.objects.filter(training_id=id)
    attr = Attribute.objects.all()
    data = {'dtrain':dtrain, 'attr':attr}
    return render(request, 'training/see_training.html', data)

def updateDataTraining(request, id):
    dtrain = TrainingValue.objects.filter(id=id).first()
    form = DataTrainingForm(instance=dtrain)
    if not dtrain:
        return redirect(reverse('training'))
    else:
        if request.method == "POST":
            form = DataTrainingForm(request.POST ,instance=dtrain)
            if form.is_valid():
                form.save()
                return redirect(reverse('training'))
    data = {'dtrain':dtrain, 'form':form}
    return render(request, 'training/update_training.html', data)

def createDataTraining(request, id):
    train = TrainingModel.objects.filter(pk=id).first()
    attr = Attribute.objects.all()
    amount_attr = attr.count()
    init_val = []
    for val in attr:
        init_val.append({
        'training_id': id,
        'attribute_id':val.id
        })
    DataTrainingFormSet = formset_factory(DataTrainingForm, extra=0)
    formset = DataTrainingFormSet(initial=init_val)
    # formset = modelformset_factory(TrainingValue, exclude=()) #update batch dari model
    if request.method == "POST":
        formset = DataTrainingFormSet(request.POST)
        if formset.is_valid():
            for form in formset:
                form.save()
            return redirect(reverse('training'))
    data = {'formset':formset}
    return render(request, 'training/create_training.html', data)

def createAttribute(request):
    return render(request, 'training/create_attribute.html')

# LAB #
def lab(request):
    labs = Lab.objects.all()
    data = {'labs': labs}
    return render(request, 'lab/index.html', data)

def createLab(request):
    form = LabForm()
    if request.method == "POST":
        form = LabForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('lab'))
    data = {'form':form}
    return render(request, 'lab/create.html', data)

def updateLab(request, id):
    # lab = Lab.objects.get(pk=id)
    lab = Lab.objects.filter(pk=id).first()
    form = LabForm(instance=lab)
    if not lab:
        return redirect(reverse('create_lab'))
    else:
        if request.method == "POST":
            form = LabForm(request.POST, instance=lab)
            if form.is_valid():
                print(lab.id)
                form.save()
                return redirect(reverse('lab'))
    data = {'lab':lab,'form':form}
    return render(request, 'lab/update.html', data)

def deleteLab(request, id):
    lab = Lab.objects.filter(pk=id).first()
    if not lab:
        return redirect(reverse('lab'))
    else:
        lab.delete()
    return redirect(reverse('lab'))

home/templates/training/create.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Training{% endblock title %}

{% block breadcrumb %}
<div class="btn-group float-right">
    <ol class="breadcrumb hide-phone p-0 m-0">
        <li class="breadcrumb-item"><a href="{% url 'dasbor' %}">Dasbor</a></li>
        <li class="breadcrumb-item"><a href="{% url 'training' %}">Training</a></li>
        <li class="breadcrumb-item active">Perbarui</li>
    </ol>
</div>
<h4 class="page-title">Perbarui Training</h4>
{%endblock%}

{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card m-b-30">
        <div class="card-body">
            <h4 class="mt-0 header-title">Training</h4>
            <p class="text-muted m-b-30 font-14">Tambah Training</p>
            <form class="" action="{% url 'create_training' %}" method="post">
              {% csrf_token %}
              {{form}}
        </div>
              <input class="btn btn-success mt-3" type="submit" name="submit" value="Simpan">
            </form>
    </div>
  </div>
</div>

{% endblock content %}

home/templates/training/create_training.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Data Training{% endblock title %}

{% block breadcrumb %}
<div class="btn-group float-right">
    <ol class="breadcrumb hide-phone p-0 m-0">
        <li class="breadcrumb-item"><a href="{% url 'dasbor' %}">Dasbor</a></li>
        <li class="breadcrumb-item"><a href="{% url 'training' %}">Training</a></li>
        <li class="breadcrumb-item active">Tambah Nilai Training</li>
    </ol>
</div>
<h4 class="page-title">Tambah Training</h4>
{%endblock%}

{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card m-b-30">
        <div class="card-body">
            <h4 class="mt-0 header-title">Data Training</h4>
            <p class="text-muted m-b-30 font-14">Tambah data latih</p>
            <form class="" action="" method="post">
              {% csrf_token %}
              {{ formset.management_form }}
              {% for form in formset %}
              {{form}}
              <hr>
              {% endfor %}
        </div>
              <input class="btn btn-success mt-3" type="submit" name="submit" value="Simpan">
            </form>
    </div>
  </div>
</div>

{% endblock content %}

home/templates/training/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Training{% endblock title %}

{% block css %}
<link href="{% static '/plugins/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static '/plugins/datatables/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}

{% block breadcrumb %}
<div class="btn-group float-right">
    <ol class="breadcrumb hide-phone p-0 m-0">
        <li class="breadcrumb-item"><a href="{% url 'dasbor' %}">Dasbor</a></li>
        <li class="breadcrumb-item active">Training</li>
    </ol>
</div>
<h4 class="page-title">Training</h4>
{%endblock%}

{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card m-b-30">
      <a href="{% url 'create_training' %}" class="btn btn-primary"><span class="fa fa-plus"></span> Training</a>
        <div class="card-body">
            <h4 class="mt-0 header-title">Training</h4>
            <p class="text-muted m-b-30 font-14">Data set training</p>
            <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                <thead>
                <tr>
                    <th>Nama</th>
                    <th>Hasil</th>
                    <th>Aksi</th>
                </tr>
                </thead>

                <tbody>
                {% for training in trainings %}
                <tr>
                    <td>{{training.name}}</td>
                    <td>{{training.result}}</td>
                    <td>
                      {% if training.trainingvalue_set.all|length == 17 %}
                      <a href="{% url 'see_data_training' training.id %}" class="btn btn-primary"><span class="fa fa-eye"></span></a>
                      {% elif training.trainingvalue_set.all|length == 0 %}
                      <a href="{% url 'create_data_training' training.id %}" class="btn btn-info"><span class="fa fa-bars"></span></a>
                      {% endif %}
                      <a href="{% url 'update_training' training.id %}" class="btn btn-warning"><span class="fa fa-pencil"></span></a>
                      <a href="{% url 'delete_training' training.id %}" class="btn btn-danger"><span class="fa fa-times"></span></a>
                    </td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block js %}
<script src="{% static '/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static '/plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static '/plugins/datatables/dataTables.responsive.min.js' %}"></script>
<script src="{% static '/plugins/datatables/responsive.bootstrap4.min.js' %}"></script>

<script src="{% static '/plugins/datatables/dataTables.buttons.min.js' %}"></script>
<script src="{% static '/plugins/datatables/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static '/plugins/datatables/jszip.min.js' %}"></script>
<script src="{% static '/plugins/datatables/pdfmake.min.js' %}"></script>
<script src="{% static '/plugins/datatables/vfs_fonts.js' %}"></script>
<script src="{% static '/plugins/datatables/buttons.html5.min.js' %}"></script>
<script src="{% static '/plugins/datatables/buttons.print.min.js' %}"></script>
<script src="{% static '/plugins/datatables/buttons.colVis.min.js' %}"></script>

<script src="{% static '/pages/datatables.init.js' %}"></script>
{% endblock js %}

home/templates/training/see_training.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Data Training{% endblock title %}

{% block css %}
<link href="{% static '/plugins/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static '/plugins/datatables/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}

{% block breadcrumb %}
<div class="btn-group float-right">
    <ol class="breadcrumb hide-phone p-0 m-0">
        <li class="breadcrumb-item"><a href="{% url 'dasbor' %}">Dasbor</a></li>
        <li class="breadcrumb-item"><a href="{% url 'training' %}">Training</a></li>
        <li class="breadcrumb-item active">Lihat Nilai Training</li>
    </ol>
</div>
<h4 class="page-title">Lihat Data Training</h4>
{%endblock%}

{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card m-b-30">
        <div class="card-body">
            <h4 class="mt-0 header-title">Lihat Data Training</h4>
            <table id="datatable-buttons" class="table table-striped table-bordered dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                <thead>
                <tr>
                    <th>Atribut</th>
                    <th>Nilai</th>
                    <th>Aksi</th>
                </tr>
                </thead>

                <tbody style="overflow-x: scroll;">
                {% for training in dtrain %}
                <tr>
                    <td>{{training.attribute_id}}</td>
                    <td>{{training.value}}</td>
                    <td><a href="{% url 'update_data_training' training.id %}" class="btn btn-warning"><span class="fa fa-pencil"></span></a></td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block js %}
<script src="{% static '/plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src="{% static '/plugins/datatables/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static '/plugins/datatables/dataTables.responsive.min.js' %}"></script>
<script src="{% static '/plugins/datatables/responsive.bootstrap4.min.js' %}"></script>

<script src="{% static '/plugins/datatables/dataTables.buttons.min.js' %}"></script>
<script src="{% static '/plugins/datatables/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static '/plugins/datatables/jszip.min.js' %}"></script>
<script src="{% static '/plugins/datatables/pdfmake.min.js' %}"></script>
<script src="{% static '/plugins/datatables/vfs_fonts.js' %}"></script>
<script src="{% static '/plugins/datatables/buttons.html5.min.js' %}"></script>
<script src="{% static '/plugins/datatables/buttons.print.min.js' %}"></script>
<script src="{% static '/plugins/datatables/buttons.colVis.min.js' %}"></script>

<script src="{% static '/pages/datatables.init.js' %}"></script>
{% endblock js %}

home/templates/training/update.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Training{% endblock title %}

{% block breadcrumb %}
<div class="btn-group float-right">
    <ol class="breadcrumb hide-phone p-0 m-0">
        <li class="breadcrumb-item"><a href="{% url 'dasbor' %}">Dasbor</a></li>
        <li class="breadcrumb-item"><a href="{% url 'training' %}">Training</a></li>
        <li class="breadcrumb-item active">Tambah</li>
    </ol>
</div>
<h4 class="page-title">Training</h4>
{%endblock%}

{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card m-b-30">
        <div class="card-body">
            <h4 class="mt-0 header-title">Training</h4>
            <p class="text-muted m-b-30 font-14">Perbarui Training</p>
            <form class="" action="{% url 'update_training' training.id %}" method="post">
              {% csrf_token %}
              {{form}}
        </div>
              <input class="btn btn-success mt-3" type="submit" name="submit" value="Simpan">
            </form>
    </div>
  </div>
</div>

{% endblock content %}

home/templates/training/update_training.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Data Training{% endblock title %}

{% block breadcrumb %}
<div class="btn-group float-right">
    <ol class="breadcrumb hide-phone p-0 m-0">
        <li class="breadcrumb-item"><a href="{% url 'dasbor' %}">Dasbor</a></li>
        <li class="breadcrumb-item"><a href="{% url 'training' %}">Training</a></li>
        <li class="breadcrumb-item active">Perbarui Nilai Training</li>
    </ol>
</div>
<h4 class="page-title">Perbarui Training</h4>
{%endblock%}

{% block content %}
<div class="row">
  <div class="col-12">
    <div class="card m-b-30">
        <div class="card-body">
            <h4 class="mt-0 header-title">Data Training</h4>
            <p class="text-muted m-b-30 font-14">Perbarui data latih</p>
            <form class="" action="" method="post">
              {% csrf_token %}
              {{form}}
        </div>
              <input class="btn btn-success mt-3" type="submit" name="submit" value="Simpan">
            </form>
    </div>
  </div>
</div>

{% endblock content %}